apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
namespace: production-devsecops-demo
resources:
  - ../../base
patches:
  - path: patch.yaml
    target:
      kind: Deployment
  - path: service-nodeport.yaml
    target:
      kind: Service
