apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  namespace: devsecops-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: devsecops-demo
          image: registry.gitlab.com/csharma/devsecops-demo:latest
