apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-demo-config
  namespace: devsecops-demo
  labels:
    app.kubernetes.io/name: devsecops-demo
    app.kubernetes.io/part-of: devsecops-demo
data:
  NODE_ENV: production
  PORT: "3000"
  TRUST_PROXY: "true"
